from .candidatoCrearVista import CandidatoCrearVista
from .candidatoDetalleVista import CandidatoDetalleVista
from .estudianteCrearVista import EstudianteCrearVista
from .estudianteDetalleVista import EstudianteDetalleVista
from .votoCrearVista import VotoList
from .votoDetalleVista import VotoDetalleVista