# Generated by Django 4.1.5 on 2023-02-18 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagen_base64', models.TextField()),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(related_name='fotos_like', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fotos',
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('foto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_fotos', to='appCitas.foto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'foto')},
            },
        ),
    ]
