# Generated by Django 4.1.5 on 2023-02-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCitas', '0002_foto_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='contenido',
            field=models.TextField(),
        ),
    ]
