# Generated by Django 4.1.5 on 2023-03-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='voto',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
